version: '3.7'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
     - 8080:8080

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
